---
- name: Install Ruby && Bundler
  hosts: all
  become: true

  tasks:
    - name: Install ruby, rubygems and required packages
      apt: 
        name: ['ruby-full', 'ruby-bundler', 'build-essential']
        state: present

