---
- name: Add unit file for puma
  template:
    src: templates/puma.service.j2
    dest: /etc/systemd/system/puma.service
  notify: Restart puma

- name: Add config for DB connection
  template:
    src: templates/db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  notify: Restart puma

- name: Enable puma service
  systemd: name=puma enabled=yes

